apiVersion: v2
type: application
name: lubelogger
description: |
  _LubeLogger_ is a web-based vehicle maintenance and fuel mileage tracker
home: https://lubelogger.com
version: 0.9.1
appVersion: "v1.4.7"
sources:
  - https://github.com/hargata/lubelog
keywords: []
annotations: {}
maintainers:
  - name: Mateusz Urbanek
    email: matueusz.urbanek.98@gmail.com
    url: http://linkedin.com/in/urbanekmateusz
