# Default values for podvm.

# -- Number of replicas for the deployment.
replicaCount: 1

# -- Firecracker configuration, in YAML format. It requires
# at least one drive, and first drive MUST BE a rootfs drive.
config:
  boot-source:
    kernel_image_path: /mnt/kernel/vmlinux.bin
    boot_args: console=ttyS0 reboot=k panic=1 pci=off
    initrd_path: null
  drives:
    - drive_id: rootfs
      partuuid: null
      is_root_device: true
      cache_type: Unsafe
      is_read_only: false
      path_on_host: /mnt/rootfs/bionic.rootfs.ext4
      io_engine: Sync
      rate_limiter: null
      socket: null
  machine-config:
    vcpu_count: 2
    mem_size_mib: 1024
    smt: false
    track_dirty_pages: false
    huge_pages: None
  cpu-config: null
  balloon: null
  network-interfaces: []
  vsock: null
  logger: null
  metrics: null
  mmds-config: null
  entropy: null

rootfs:
  image:
    # -- Registry and repository for the rootfs image.
    repository: ""
    # -- Tag for the image.
    tag: ""
    # -- Image pull policy.
    pullPolicy: IfNotPresent

kernel:
  image:
    # -- Registry and repository for the kernel image.
    repository: ""
    # -- Tag for the image.
    tag: ""
    # -- Image pull policy.
    pullPolicy: IfNotPresent

# -- Additional volumes.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volumeMounts.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

firecracker:
  image:
    # -- Registry and repository for the podvm image.
    repository: ghcr.io/anza-labs/library/firecracker
    # -- Tag for the image.
    tag: "1.10.1"
    # -- Image pull policy.
    pullPolicy: IfNotPresent

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

kvm:
  # -- Name of the KVM device requested. Should be one of:
  # `"devices.kubevirt.io/kvm"` when using https://github.com/kubevirt/kubernetes-device-plugins,
  # `"devices.anza-labs.dev/kvm"` when using https://github.com/anza-labs/kubelet-device-plugins.
  name: "devices.anza-labs.dev/kvm"

tun:
  # -- Name of the TUN device requested.
  # `"devices.anza-labs.dev/tun"` when using https://github.com/anza-labs/kubelet-device-plugins.
  name: "devices.anza-labs.dev/tun"

# -- Secrets for pulling images.
imagePullSecrets: []
# -- Override for the name.
nameOverride: ""
# -- Override for the full name.
fullnameOverride: ""

# -- Annotations to be added to the pods.
podAnnotations: {}
# -- Labels to be added to the pods.
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

# -- Node selector for the pods.
nodeSelector: {}

# -- Tolerations for the pods.
tolerations: []

# -- Affinity settings for the pods.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
              - amd64
              - arm64
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
