{{- if .Values.backup.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pocket-id.backupSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pocket-id.labels" . | nindent 4 }}
data:
  litestream.yaml: |
    addr: "0.0.0.0:8081"
    logging:
      level: {{ .Values.backup.logging.level }}
      type: {{ .Values.backup.logging.type }}
      stderr: {{ .Values.backup.logging.stderr }}
    {{- if .Values.backup.secret.accessKey }}
    access-key-id: "$ACCESS_KEY"
    {{- end }}
    {{- if .Values.backup.secret.secretKey }}
    secret-access-key: "$SECRET_KEY"
    {{- end }}
    dbs:
      - path: /data/pocket-id.db
        {{- if .Values.backup.monitorInterval }}
        monitor-interval: {{ .Values.backup.monitorInterval }}
        {{- end }}
        {{- if .Values.backup.checkpointInterval }}
        checkpoint-interval: {{ .Values.backup.checkpointInterval }}
        {{- end }}
        {{- if .Values.backup.busyTimeout }}
        busy-timeout: {{ printf .Values.backup.busyTimeout }}
        {{- end }}
        {{- if .Values.backup.minCheckpointPageCount }}
        min-checkpoint-page-count: {{ .Values.backup.minCheckpointPageCount }}
        {{- end }}
        {{- if .Values.backup.maxCheckpointPageCount }}
        max-checkpoint-page-count: {{ .Values.backup.maxCheckpointPageCount }}
        {{- end }}
        replicas:
    {{- range $i, $val := .Values.backup.secret.replicas }}
          - type: "s3"
            path: "{{ $val.path }}"
            {{- if $val.accessKey }}
            access-key-id: "{{ printf "$REPLICA_%d_ACCESS_KEY" $i }}"
            {{- end }}
            {{- if $val.secretKey }}
            secret-access-key: "{{ printf "$REPLICA_%d_SECRET_KEY" $i }}"
            {{- end }}
            {{- if $val.region }}
            region: "{{ $val.region }}"
            {{- end }}
            {{- if $val.bucket }}
            bucket: "{{ $val.bucket }}"
            {{- end }}
            {{- if $val.endpoint }}
            endpoint: "{{ $val.endpoint }}"
            {{- end }}
            force-path-style: {{ default false $val.forcePathStyle }}
            skip-verify: {{ default false $val.skipVerify }}
    {{- end }}
{{- end }}
