{{- $svcPort := .Values.service.port -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pocket-id.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pocket-id.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $svcPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pocket-id.selectorLabels" . | nindent 4 }}
