apiVersion: v2
type: application
name: pocket-id
description: |
  _pocket-id_ is a simple and easy-to-use OIDC provider that allows users to authenticate
  with their passkeys to your services.
home: https://pocket-id.org
version: 0.2.1
appVersion: "v0.51.1"
sources:
  - https://github.com/pocket-id/pocket-id
keywords: []
annotations: {}
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
