apiVersion: v2
deprecated: true # Mark as deprecated, no longer developed
type: application
name: hosted-control-plane
description: |
  _hosted-control-plane_ is a PoC/testing ground for any improvements that might
  reach Cluster API Control Plane Provider KinK manifests.
home: https://anza-labs.github.io/kink
version: 1.0.0
appVersion: "v1.33.1"
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: ">=v1.16.0"
    condition: cert-manager.deploy
